#!/usr/bin/env python
import os
import sys
import koji
import logging
from darkimporter.darkdaemon import Daemon
from darkimporter.libimporter import produce_jobs
from darkimporter.libimporter import create_rundir


class DarkDaemon(Daemon):
    def run(self):
        """
        The daemon process
        """
        produce_jobs(int(sys.argv[2]))
 

if __name__ == '__main__':
    daemon = None 
    create_rundir()
    if len(sys.argv) >= 2:
        daemon = DarkDaemon('/var/run/darkserver/darkproducer.pid')
        
        if 'start' == sys.argv[1]:
            daemon.start()
        else:
            print "Unknown command"
            sys.exit(2)
        sys.exit(0)
    else:
        print "usage: %s start" % sys.argv[0]
        sys.exit(2)
