#!/usr/bin/env python
import os
import sys
import atexit
import logging
import readline
from darkimporter.dashboard import Application

#Code to write the history file
history_file = os.path.expanduser('~/.darkdashboard_history')
if os.path.exists(history_file):
    readline.read_history_file(history_file)

atexit.register(readline.write_history_file, history_file)

if __name__ == '__main__':

    app = Application()
    app.cmdloop()