#!/usr/bin/env python
import os
import sys
import logging
from darkimporter.darkdaemon import Daemon
from darkimporter.libimporter import monitor_buildqueue
from darkimporter.libimporter import create_rundir

logging.basicConfig(filename='/var/log/darkserver.log', level=logging.INFO,\
                        format='%(asctime)s:%(name)s:%(levelname)s:%(message)s')


class DarkDaemon(Daemon):
    def run(self):
        """
        The daemon process
        """
        monitor_buildqueue()


if __name__ == '__main__':

    
    daemon = None 
    create_rundir()
    if len(sys.argv) == 2:
        daemon = DarkDaemon('/var/run/darkserver/darkbuildqueue.pid')
        if 'start' == sys.argv[1]:
            daemon.start()
        else:
            print "Unknown command"
            sys.exit(2)
        sys.exit(0)
    if len(sys.argv) == 3:
        if 'start' == sys.argv[1]:
            daemon = DarkDaemon('/var/run/darkserver/darkbuildqueue%s.pid' % sys.arv[2])
            daemon.start()
            sys.exit(0)
    else:
        print "usage: %s start" % sys.argv[0]
        sys.exit(2)
