#!/usr/bin/env python
import sys
import logging
from darkimporter.darkdaemon import Daemon
from darkimporter.libimporter import monitor_buildqueue

class DarkDaemon(Daemon):
    def run(self):
        """
        The daemon process
        """
        monitor_buildqueue(self.logger)


if __name__ == '__main__':
    logging.basicConfig(filename='/tmp/darkbuildqueue.log', level=logging.INFO,\
                        format='%(asctime)s:%(name)s:%(levelname)s:%(message)s')
    
    daemon = None 
    if len(sys.argv) == 2:
        logger = logging.getLogger("buildworker")
        daemon = DarkDaemon('/tmp/darkbuildqueue.pid', logger)
        if 'start' == sys.argv[1]:
            daemon.start()
        elif 'stop' == sys.argv[1]:
            daemon.stop()
        elif 'restart' == sys.argv[1]:
            daemon.restart()
        else:
            print "Unknown command"
            sys.exit(2)
        sys.exit(0)
    if len(sys.argv) == 3:
        if 'start' == sys.argv[1]:
            logger = logging.getLogger("buildworker%s" % sys.argv[2])
            daemon = DarkDaemon('/tmp/darkbuildqueue%s.pid' % sys.arv[2], logger)
            daemon.start()
            sys.exit(0)
    else:
        print "usage: %s start|stop|restart" % sys.argv[0]
        sys.exit(2)
