#!/usr/bin/env python
import sys
import koji
import logging
from darkimporter.darkdaemon import Daemon
from darkimporter.libimporter import produce_jobs
from darkimporter.libimporter import create_rundir

class DarkDaemon(Daemon):
    def run(self):
        """
        The daemon process
        """
        produce_jobs(self.logger, int(sys.argv[2]))
 

if __name__ == '__main__':
    logging.basicConfig(filename='/tmp/darkproducer.log', level=logging.INFO,
                        format='%(asctime)s:%(name)s:%(levelname)s:%(message)s')
    daemon = None 
    create_rundir()
    if len(sys.argv) >= 2:
        logger = logging.getLogger("producer")
        daemon = DarkDaemon('/var/run/darkserver/darkproducer.pid', logger)
        
        if 'start' == sys.argv[1]:
            daemon.start()
        else:
            print "Unknown command"
            sys.exit(2)
        sys.exit(0)
    else:
        print "usage: %s start" % sys.argv[0]
        sys.exit(2)
