#!/usr/bin/env python
import sys
import logging
from darkimporter.darkdaemon import Daemon
from darkimporter.libimporter import monitor_buildqueue
from darkimporter.libimporter import create_rundir

class DarkDaemon(Daemon):
    def run(self):
        """
        The daemon process
        """
        monitor_buildqueue(self.logger)


if __name__ == '__main__':
    logging.basicConfig(filename='/tmp/darkbuildqueue.log', level=logging.INFO,\
                        format='%(asctime)s:%(name)s:%(levelname)s:%(message)s')
    
    daemon = None 
    create_rundir()
    if len(sys.argv) == 2:
        logger = logging.getLogger("buildworker")
        daemon = DarkDaemon('/var/run/darkserver/darkbuildqueue.pid', logger)
        if 'start' == sys.argv[1]:
            daemon.start()
        else:
            print "Unknown command"
            sys.exit(2)
        sys.exit(0)
    if len(sys.argv) == 3:
        if 'start' == sys.argv[1]:
            logger = logging.getLogger("buildworker%s" % sys.argv[2])
            daemon = DarkDaemon('/var/run/darkserver/darkbuildqueue%s.pid' % sys.arv[2], logger)
            daemon.start()
            sys.exit(0)
    else:
        print "usage: %s start" % sys.argv[0]
        sys.exit(2)
