#!/usr/bin/env python
import sys
import redis
import time
import koji
import logging
from darkdaemon import Daemon

class DarkDaemon(Daemon):
    def run(self):
        """
        The daemon process
        """
        kojiurl="http://koji.fedoraproject.org/kojihub"
        kc = koji.ClientSession(kojiurl, {'debug': False, 'password': None,\
                            'debug_xmlrpc': False, 'user': None})
        rdb = redis.Redis(host='localhost', port=6379, db=1)
        while True:
            #mainurl = 'http://koji.fedoraproject.org/koji/buildinfo?buildID=%s' % idx
            #req = requests.get(mainurl)
            if rdb.llen("jobqueue") == 0:
                self.logger.info("Sleeping, no jobqueue job")
                time.sleep(5)
                continue
            url = rdb.rpop("jobqueue")
            idx = int(url.split('=')[-1])
            try:
                self.logger.info("Imported %s" % idx)
                time.sleep(10)
                
            except Exception as err:
                self.logger.error(err)
    

if __name__ == '__main__':
    logging.basicConfig(filename='darkjobqueue.log', level=logging.INFO,\
                        format='%(asctime)s:%(name)s:%(levelname)s:%(message)s')
    daemon = None 
    if len(sys.argv) == 2:
        logger = logging.getLogger("jobworker")
        daemon = DarkDaemon('/tmp/darkjobqueue.pid', logger)
        if 'start' == sys.argv[1]:
            daemon.start()
        elif 'stop' == sys.argv[1]:
            daemon.stop()
        elif 'restart' == sys.argv[1]:
            daemon.restart()
        else:
            print "Unknown command"
            sys.exit(2)
        sys.exit(0)
    if len(sys.argv) == 3:
        logger = logging.getLogger("jobworker%s" % sys.argv[2])
        daemon = DarkDaemon('/tmp/darkjobqueue%s.pid' % sys.argv[2], logger)
        if 'start' == sys.argv[1]:
            daemon.start()
        elif 'stop' == sys.argv[1]:
            daemon.stop() 
        sys.exit(0)
    else:
        print "usage: %s start|stop|restart" % sys.argv[0]
        sys.exit(2)